### ISSUE TITLE
@abc.xyz\angular-monaco-editor-loader\index.ts is not part of the compilation output

### ISSUE THREAD

**Issue by mostwired** [leolorenzoluis/xyz.MonacoEditorLoader#15]
Using Angular CLI 1.6 with Angular 5, perform prerequisite setup as specified, but get an error on ng build:

ERROR in ./node_modules/@abc.xyz/angular-monaco-editor-loader/index.ts
Module build failed: Error: C:\Projects\CSI\ValidationCustomScripting\vcs-mod\node_modules\@abc.xyz\angular-monaco-editor-loader\index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (C:\Projects\CSI\ValidationCustomScripting\vcs-mod\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:649:23)
...

**Comment by JulCesWhat** [comment]
Fixed it with https://github.com/JulCesWhat/angular5-monaco-editor-loader

**Comment by leolorenzoluis** [comment]
@JulCesWhat Thanks for literally copying everything and not submitting a pull request 👍 

@mostwired Sorry I'm currently in vacation right now. Will fix it when I am back 💯

**Comment by leolorenzoluis** [comment]
@mostwired I've updated the library to support Angular 5. Please try again.
