### ISSUE TITLE
Electron issue

### ISSUE THREAD

**Issue by nagug** [leolorenzoluis/xyz.MonacoEditorLoader#35]
I am trying to use the loader with electron. in browser the app works perfectly, but when it comes to electron. following error is thrown
```

TypeError: window.require.config is not a function
TypeError: window.require.config is not a function
    at onGotAmdLoader (vendor.js:28)
```

Any directions to explore is really appreciated.. looks like some clash of window objects...

**Comment by leolorenzoluis** [comment]
Hmm, thanks for reporting. Do you have any other conflicting packages? I have not tested it in Electron.

**Comment by nagug** [comment]
No it basic angular-electron boilerplate.
